Adding scix_id field to records DB in master pipeline
adsabs/ADSMasterPipeline pull request #183
Opened 2024-11-11 18:47 UTC by mugdhapolimera

2024-11-13 16:34 UTC, tjacovich requested changes
Looking good so far. A couple of smaller comments and then we just need some unit tests and we should be good to go.

2025-02-04 15:33 UTC, tjacovich approved these changes
Looks good. A question about the random change in `dev-requirements.txt`, but otherwise should be good to resolve conflicts and merge.

2025-02-04 15:33 UTC, tjacovich commented on dev-requirements.txt
> +testing.postgresql==1.3.0
Do we know what is different between these lines?

2025-02-04 22:54 UTC, mugdhapolimera commented on dev-requirements.txt
> +testing.postgresql==1.3.0
git diff is not catching anything locally, so I'm not sure. I think it may be some space/return character difference?

2025-02-04 23:04 UTC, merged